export const allSpecialties = [
    // Bachelor
    {
        id: 'medicine', category: 'bachelor', name: 'الطب البشري', nameEn: 'Medicine',
        icon: 'fas fa-stethoscope', color: '#E74C3C',
        image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=2070&auto=format&fit=crop',
        duration: '6 سنوات', language: 'إنجليزي / تركي',
        description: 'دراسة الطب البشري في الجامعات التركية الخاصة مع أحدث المناهج والتدريب السريري',
        tags: ['medical'],
    },
    {
        id: 'dentistry', category: 'bachelor', name: 'طب الأسنان', nameEn: 'Dentistry',
        icon: 'fas fa-tooth', color: '#3498DB',
        image: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=2070&auto=format&fit=crop',
        duration: '5 سنوات', language: 'إنجليزي / تركي',
        description: 'تخصص طب الأسنان من أكثر التخصصات طلباً في الجامعات التركية مع تدريب عملي متقدم',
        tags: ['medical'],
    },
    {
        id: 'pharmacy', category: 'bachelor', name: 'الصيدلة', nameEn: 'Pharmacy',
        icon: 'fas fa-pills', color: '#27AE60',
        image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?q=80&w=2079&auto=format&fit=crop',
        duration: '5 سنوات', language: 'إنجليزي / تركي',
        description: 'دراسة علوم الصيدلة والأدوية في بيئة أكاديمية متطورة مع مختبرات حديثة',
        tags: ['medical'],
    },
    {
        id: 'software-engineering', category: 'bachelor', name: 'هندسة البرمجيات', nameEn: 'Software Engineering',
        icon: 'fas fa-code', color: '#9B59B6',
        image: 'https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?q=80&w=2070&auto=format&fit=crop',
        duration: '4 سنوات', language: 'إنجليزي',
        description: 'تعلم تطوير البرمجيات وعلوم الحاسوب مع أحدث التقنيات والمنهجيات',
        tags: ['engineering'],
    },
    {
        id: 'architecture', category: 'bachelor', name: 'الهندسة المعمارية', nameEn: 'Architecture',
        icon: 'fas fa-drafting-compass', color: '#E67E22',
        image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=2031&auto=format&fit=crop',
        duration: '4 سنوات', language: 'إنجليزي / تركي',
        description: 'دراسة التصميم المعماري والتخطيط العمراني في جامعات تركية عريقة',
        tags: ['engineering'],
    },
    {
        id: 'business-admin', category: 'bachelor', name: 'إدارة الأعمال', nameEn: 'Business Administration',
        icon: 'fas fa-briefcase', color: '#2C3E50',
        image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=2070&auto=format&fit=crop',
        duration: '4 سنوات', language: 'إنجليزي / تركي',
        description: 'تعلم أساسيات إدارة الأعمال والتسويق والتمويل في بيئة دولية',
        tags: [],
    },
    {
        id: 'ai-engineering', category: 'bachelor', name: 'هندسة الذكاء الاصطناعي', nameEn: 'AI Engineering',
        icon: 'fas fa-robot', color: '#1ABC9C',
        image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=2070&auto=format&fit=crop',
        duration: '4 سنوات', language: 'إنجليزي',
        description: 'تخصص حديث يجمع بين علوم الحاسوب والذكاء الاصطناعي وتعلم الآلة',
        tags: ['engineering'],
    },
    {
        id: 'physiotherapy', category: 'bachelor', name: 'العلاج الطبيعي', nameEn: 'Physiotherapy',
        icon: 'fas fa-walking', color: '#16A085',
        image: 'https://images.unsplash.com/photo-1576091160550-2187d80a851f?q=80&w=2070&auto=format&fit=crop',
        duration: '4 سنوات', language: 'إنجليزي / تركي',
        description: 'دراسة علوم التأهيل والعلاج الطبيعي مع تدريب سريري متخصص',
        tags: ['medical'],
    },
    {
        id: 'nursing', category: 'bachelor', name: 'التمريض', nameEn: 'Nursing',
        icon: 'fas fa-user-nurse', color: '#E91E63',
        image: 'https://images.unsplash.com/photo-1511174511562-5f7f18b874f8?q=80&w=2070&auto=format&fit=crop',
        duration: '4 سنوات', language: 'إنجليزي / تركي',
        description: 'برنامج تمريض شامل يؤهلك للعمل في المستشفيات والمراكز الصحية الدولية',
        tags: ['medical'],
    },
    {
        id: 'civil-engineering', category: 'bachelor', name: 'الهندسة المدنية', nameEn: 'Civil Engineering',
        icon: 'fas fa-hard-hat', color: '#FF9800',
        image: 'https://images.unsplash.com/photo-1531834685032-c34bf0d84c71?q=80&w=1997&auto=format&fit=crop',
        duration: '4 سنوات', language: 'إنجليزي / تركي',
        description: 'دراسة تصميم وبناء المنشآت والبنية التحتية مع أحدث البرامج الهندسية',
        tags: ['engineering'],
    },
    {
        id: 'psychology', category: 'bachelor', name: 'علم النفس', nameEn: 'Psychology',
        icon: 'fas fa-brain', color: '#673AB7',
        image: 'https://images.unsplash.com/photo-1471820984852-c0e816a4b504?q=80&w=2070&auto=format&fit=crop',
        duration: '4 سنوات', language: 'إنجليزي / تركي',
        description: 'فهم السلوك البشري والصحة النفسية مع تطبيقات عملية وتدريب ميداني',
        tags: [],
    },
    {
        id: 'new-media', category: 'bachelor', name: 'الإعلام الجديد', nameEn: 'New Media',
        icon: 'fas fa-photo-video', color: '#00BCD4',
        image: 'https://images.unsplash.com/photo-1626379953822-baec19c3accd?q=80&w=2070&auto=format&fit=crop',
        duration: '4 سنوات', language: 'إنجليزي / تركي',
        description: 'دراسة الاتصال الرقمي والإعلام الحديث وإنتاج المحتوى الإبداعي',
        tags: [],
    },
    // Master
    {
        id: 'mba', category: 'master', name: 'ماجستير إدارة الأعمال MBA', nameEn: 'MBA',
        icon: 'fas fa-chart-line', color: '#2C3E50',
        image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2015&auto=format&fit=crop',
        duration: 'سنتان', language: 'إنجليزي / تركي',
        description: 'برنامج ماجستير متقدم في إدارة الأعمال مع تخصصات متنوعة',
        tags: [],
    },
    {
        id: 'ai-masters', category: 'master', name: 'ماجستير الذكاء الاصطناعي', nameEn: 'AI Masters',
        icon: 'fas fa-microchip', color: '#1ABC9C',
        image: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?q=80&w=2070&auto=format&fit=crop',
        duration: 'سنتان', language: 'إنجليزي',
        description: 'تعمق في تقنيات الذكاء الاصطناعي والتعلم العميق وتحليل البيانات',
        tags: ['engineering'],
    },
    {
        id: 'industrial-engineering', category: 'master', name: 'ماجستير الهندسة الصناعية', nameEn: 'Industrial Engineering',
        icon: 'fas fa-industry', color: '#FF5722',
        image: 'https://images.unsplash.com/photo-1581093458791-9f302e683800?q=80&w=2070&auto=format&fit=crop',
        duration: 'سنتان', language: 'إنجليزي / تركي',
        description: 'دراسة تحسين العمليات الصناعية وإدارة سلاسل الإمداد',
        tags: ['engineering'],
    },
    {
        id: 'it-masters', category: 'master', name: 'ماجستير تكنولوجيا المعلومات', nameEn: 'IT Masters',
        icon: 'fas fa-server', color: '#607D8B',
        image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072&auto=format&fit=crop',
        duration: 'سنتان', language: 'إنجليزي',
        description: 'تطوير مهاراتك في البنية التحتية التقنية وأمن المعلومات والشبكات',
        tags: ['engineering'],
    },
    {
        id: 'public-health', category: 'master', name: 'ماجستير الصحة العامة', nameEn: 'Public Health',
        icon: 'fas fa-hospital', color: '#4CAF50',
        image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?q=80&w=2070&auto=format&fit=crop',
        duration: 'سنتان', language: 'إنجليزي / تركي',
        description: 'دراسة السياسات الصحية وإدارة المؤسسات الصحية والأوبئة',
        tags: ['medical'],
    },
    {
        id: 'international-relations', category: 'master', name: 'ماجستير العلاقات الدولية', nameEn: 'International Relations',
        icon: 'fas fa-globe', color: '#3F51B5',
        image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?q=80&w=2069&auto=format&fit=crop',
        duration: 'سنتان', language: 'إنجليزي / تركي',
        description: 'دراسة السياسة الدولية والدبلوماسية والمنظمات الدولية',
        tags: [],
    },
    // PhD
    {
        id: 'phd-business', category: 'phd', name: 'دكتوراه إدارة الأعمال', nameEn: 'PhD Business Admin',
        icon: 'fas fa-user-tie', color: '#34495E',
        image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?q=80&w=2074&auto=format&fit=crop',
        duration: '3-4 سنوات', language: 'إنجليزي / تركي',
        description: 'برنامج بحثي متقدم في إدارة الأعمال مع إمكانية النشر الأكاديمي',
        tags: [],
    },
    {
        id: 'phd-aerospace', category: 'phd', name: 'دكتوراه هندسة الطيران', nameEn: 'PhD Aerospace Eng',
        icon: 'fas fa-plane', color: '#0277BD',
        image: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?q=80&w=2070&auto=format&fit=crop',
        duration: '3-4 سنوات', language: 'إنجليزي',
        description: 'بحث متقدم في تصميم الطائرات وهندسة الفضاء',
        tags: ['engineering'],
    },
    {
        id: 'phd-political-science', category: 'phd', name: 'دكتوراه العلوم السياسية', nameEn: 'PhD Political Science',
        icon: 'fas fa-landmark', color: '#795548',
        image: 'https://images.unsplash.com/photo-1541872703-74c5963631df?q=80&w=2070&auto=format&fit=crop',
        duration: '3-4 سنوات', language: 'إنجليزي / تركي',
        description: 'بحث أكاديمي معمق في العلوم السياسية والإدارة العامة',
        tags: [],
    },
    {
        id: 'phd-dentistry', category: 'phd', name: 'دكتوراه طب الأسنان', nameEn: 'PhD Dentistry',
        icon: 'fas fa-teeth', color: '#00897B',
        image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?q=80&w=2068&auto=format&fit=crop',
        duration: '4-5 سنوات', language: 'إنجليزي / تركي',
        description: 'أبحاث متقدمة في علوم طب الأسنان والتركيبات السنية',
        tags: ['medical'],
    },
    // Diploma
    {
        id: 'anesthesia-diploma', category: 'diploma', name: 'دبلوم التخدير', nameEn: 'Anesthesia Diploma',
        icon: 'fas fa-syringe', color: '#E53935',
        image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=2080&auto=format&fit=crop',
        duration: 'سنتان', language: 'تركي',
        description: 'تأهيل متخصص في علوم التخدير والعناية المركزة',
        tags: ['medical'],
    },
    {
        id: 'optics-diploma', category: 'diploma', name: 'دبلوم البصريات', nameEn: 'Optics Diploma',
        icon: 'fas fa-glasses', color: '#5C6BC0',
        image: 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?q=80&w=2070&auto=format&fit=crop',
        duration: 'سنتان', language: 'تركي',
        description: 'دراسة علوم البصريات وتركيب العدسات والنظارات',
        tags: ['medical'],
    },
    {
        id: 'computer-programming', category: 'diploma', name: 'دبلوم برمجة الحاسوب', nameEn: 'Computer Programming',
        icon: 'fas fa-laptop-code', color: '#0097A7',
        image: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?q=80&w=2031&auto=format&fit=crop',
        duration: 'سنتان', language: 'إنجليزي / تركي',
        description: 'تعلم أساسيات البرمجة وتطوير التطبيقات وقواعد البيانات',
        tags: ['engineering'],
    },
    {
        id: 'culinary-arts', category: 'diploma', name: 'دبلوم فنون الطبخ', nameEn: 'Culinary Arts',
        icon: 'fas fa-utensils', color: '#FF6F00',
        image: 'https://images.unsplash.com/photo-1556910103-1c02745a30bf?q=80&w=2070&auto=format&fit=crop',
        duration: 'سنتان', language: 'تركي',
        description: 'تعلم فنون الطبخ العالمية والتركية مع تدريب عملي في مطابخ احترافية',
        tags: [],
    },
    {
        id: 'pharmacy-services', category: 'diploma', name: 'دبلوم الخدمات الصيدلية', nameEn: 'Pharmacy Services',
        icon: 'fas fa-prescription-bottle', color: '#43A047',
        image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=2073&auto=format&fit=crop',
        duration: 'سنتان', language: 'تركي',
        description: 'تأهيل للعمل في الصيدليات كمساعد صيدلي محترف',
        tags: ['medical'],
    },
    {
        id: 'medical-lab', category: 'diploma', name: 'دبلوم المختبرات الطبية', nameEn: 'Medical Lab',
        icon: 'fas fa-vial', color: '#AB47BC',
        image: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?q=80&w=2070&auto=format&fit=crop',
        duration: 'سنتان', language: 'تركي',
        description: 'دراسة التحاليل المخبرية والفحوصات الطبية في مختبرات حديثة',
        tags: ['medical'],
    },
];